apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goflow-kube
  name: goflow-kube
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goflow-kube
  template:
    metadata:
      labels:
        app: goflow-kube
    spec:
      volumes:
        - name: config-vol
          configMap:
            name: loki-exporter-config
      containers:
        - command:
            - /bin/sh
            - -c
            - /goflow-kube -loglevel "info" -stdinsourceformat "pb" -listen "netflow://:2055" -lokiconfig /etc/loki-exporter/loki-exporter.yaml
          image: quay.io/netobserv/goflow-kube:dev
          imagePullPolicy: IfNotPresent
          name: goflow-kube
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          volumeMounts:
              - mountPath: /etc/loki-exporter
                name: config-vol
      serviceAccountName: goflow-kube
---
apiVersion: v1
kind: Service
metadata:
  name: goflow-kube
  namespace: default
  labels:
    app: goflow-kube
spec:
  ports:
    - port: 2055
      protocol: UDP
  selector:
    app: goflow-kube
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-exporter-config
data:
  loki-exporter.yaml: |
    labels:
      - SrcNamespace
      - SrcWorkload
      - DstNamespace
      - DstWorkload
    ignoreList:
      - NextHop
      - NextHopAS
    printInput: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: goflow-kube
  name: goflow-kube
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: goflow-kube
  name: goflow-kube
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: goflow-kube
subjects:
  - kind: ServiceAccount
    name: goflow-kube
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: goflow-kube
  name: goflow-kube
rules:
  - apiGroups:
      - ""
      - "apps"
    resources:
      - pods
      - replicasets
      - services
    verbs:
      - list
      - get
      - watch

